---
- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - pi_update_packages

- name: Upgrade packages
  become: true
  apt:
    upgrade: yes
    autoremove: yes
  register: result
  tags:
    - pi_update_packages

- name: Fix broken packages
  become: true
  command: apt-get -f install
  when: result.failed
  tags:
    - pi_update_packages

- name: Dist-upgrade packages
  become: true
  command: apt-get dist-upgrade
  when: result.failed
  tags:
    - pi_update_packages

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags:
    - pi_update_packages

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - pi_update_packages

# Install required packages
- name: install packages for Raspberry Pi
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"
  tags:
    - pi_install_packages

# Uninstall Raspbian bloat
- name: remove raspbian bloat
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - wolfram-engine
      - libreoffice*
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo
      - gpicview
      - penguinspuzzle
  tags:
    - pi_remove_bloat
