---
- name: disable ssh login for user pi
  lineinfile:
    dest=/etc/ssh/sshd_config
    line="DenyUsers pi"
    state=present
  when: disable_pi_user
  notify: Reboot Pi
  tags:
    - disable_pi_user

