---
#
# Configure firewall
#
- name: allow SSH through UFW
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    log: yes
  tags:
    - security

- name: allow mDNS through UFW
  ufw:
    rule: allow
    to_ip: 224.0.0.251
    proto: igmp
    log: no
  tags:
    - security

- name: drop multicast without logging
  ufw:
    rule: deny
    to_ip: 224.0.0.1
    log: no
  tags:
    - security

- name: set default incoming UFW policy to deny
  ufw:
    direction: incoming
    policy: deny
  tags:
    - security

- name: set default outgoing UFW policy to allow
  ufw:
    direction: outgoing
    policy: allow
  tags:
    - security

- name: enable UFW
  ufw:
    state: "enabled"
    logging: "on"
  tags:
    - security
