---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: balenalib/raspberry-pi-debian:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
