---
name: Increment Tag

on:
  pull_request:
    types: [closed]

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      run: |
        current_tag=$(git describe --tags --abbrev=0)

    - name: Increment tag
      run: |
        new_tag=$(echo $current_tag | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
        echo "Incrementing tag from $current_tag to $new_tag"
        git tag $new_tag

    - name: Push new tag
      run: |
        git push origin $new_tag